version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payload
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    networks:
      - payload
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_PASSWORD=payload
      - POSTGRES_DB=payload
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payload -d payload"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  pgdata:

networks:
  payload:
    external: false