version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_PASSWORD=payload
      - POSTGRES_DB=payload
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules: