version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payload
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    networks:
      - payload
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_PASSWORD=payload
      - POSTGRES_DB=payload
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  payload:
    external: false